#!/usr/bin/env bash
# =============================================================================
# CylinderUI - start services in background (llama-swap, agent-if-present, router)
# PIDs in run/, logs in logs/. Idempotent: won't double-start a live service.
# =============================================================================
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
cyl_init_paths; cyl_load_env; cyl_detect

start_svc() {  # start_svc <name> <port> <logfile> -- rest of args = command
  local name="$1" port="$2" logf="$3"; shift 3
  if cyl_is_running "$name"; then ok "$name already running (pid $(cat "$(cyl_pidfile "$name")"))"; return 0; fi
  if cyl_port_busy "$port"; then warn "$name: port $port already in use by another process -- skipping start"; return 0; fi
  log "starting $name on :$port"
  ( "$@" >>"$logf" 2>&1 & echo $! >"$(cyl_pidfile "$name")" )
  sleep 1
  cyl_is_running "$name" && ok "$name up (pid $(cat "$(cyl_pidfile "$name")"), log: $logf)" \
                         || warn "$name may have failed to start -- see $logf"
}

# ---- 1. llama-swap (model swapper + inference) ------------------------------
SWAP_BIN="$VENDOR_DIR/llama-swap"
SWAP_CFG="$VENDOR_DIR/llama-swap.yaml"
if [ -x "$SWAP_BIN" ]; then
  if [ ! -f "$SWAP_CFG" ]; then
    # Minimal generated config pointing at the built llama-server + models dir.
    cat >"$SWAP_CFG" <<YAML
# Auto-generated by CylinderUI run.sh. Edit to add models.
models:
  "${AGENT_MODEL}":
    cmd: >
      ${LLAMACPP_DIR}/build/bin/llama-server
      -m ${MODELS_DIR}/${MODEL_FILE}
      --port \${PORT} -ngl 99
YAML
    ok "generated $SWAP_CFG"
  fi
  start_svc llama-swap "$LLAMA_SWAP_PORT" "$LOG_DIR/llama-swap.log" \
    "$SWAP_BIN" --listen "127.0.0.1:${LLAMA_SWAP_PORT}" --config "$SWAP_CFG"
else
  warn "llama-swap binary missing ($SWAP_BIN) -- inference disabled. Re-run install.sh."
fi

# ---- 2. agent (native-agent-v2) if present ----------------------------------
if [ -n "$AGENT_DIR" ] && [ -f "$AGENT_DIR/app/main.py" ]; then
  # Agent listens on loopback only; the router (8088) is the public front.
  start_svc agent "$AGENT_PORT" "$LOG_DIR/agent.log" \
    env ROUTER_URL="$ROUTER_URL" LLAMA_SWAP_URL="$LLAMA_SWAP_URL" AGENT_MODEL="$AGENT_MODEL" \
        LOG_DIR="$LOG_DIR" \
    "$VENV_DIR/bin/python" -m uvicorn app.main:app --host 127.0.0.1 --port "$AGENT_PORT" \
    --app-dir "$AGENT_DIR"
else
  warn "agent not found -- Visões / Model Store / Benchmark / RAG unavailable (router-only mode)."
fi

# ---- 3. router (UI + /api proxy) -- the public entrypoint --------------------
if [ -f "$ROUTER_DIR/router.py" ]; then
  start_svc router "$PROMPT_ROUTER_PORT" "$LOG_DIR/router.log" \
    env PROMPT_ROUTER_PORT="$PROMPT_ROUTER_PORT" PROMPT_ROUTER_HOST="$PROMPT_ROUTER_HOST" \
        LLAMA_SWAP_URL="$LLAMA_SWAP_URL" \
    "$VENV_DIR/bin/python" "$ROUTER_DIR/router.py"
else
  die "router.py not found at $ROUTER_DIR -- cannot start the UI"
fi

echo; ok "Open: http://localhost:${PROMPT_ROUTER_PORT}"
